#spring:
#  datasource:
#      url: jdbc:sqlserver://raithannadairy.database.windows.net:1433;database=RaithannaMilkDairy;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#      username: rd345
#      password: seca6123@
#
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
#server:
#  port: 9193
#
